language: node_js
node_js: node

env:
  - ELM_VERSION=0.19.0 ELM_TEST=0.19.0

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
    - sysconfcpus
    - $HOME/.npm
    - $HOME/.elm

before_install:
  - | # build time improvement see: https://git.io/vQcqz
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST
  - npm install -g elm-format

script:
  - ./ci-check-no-warnings.sh
  - elm-format --validate src --elm-version=0.19
  - elm-test --verbose
